"""Canonical data model. TRS sections 5 and 7."""

from .chunk import ChunkRecord
from .component import ComponentInstance, SourceDocument
from .encoding import UnencodableValueError, encode_value
from .enums import (
    CATEGORY_TO_TAB,
    CellFlag,
    ComponentCategory,
    ConflictClass,
    ConflictStatus,
    DocumentType,
    EfficiencyWeighting,
    MeasurementBasis,
    PowerSide,
    ResolutionAction,
    RteBoundary,
    Severity,
    SourceTier,
    StandardsRegime,
    ToleranceCondition,
    ToleranceKind,
    ToleranceRule,
    UnresolvedStatus,
    WorkbookTab,
)
from .extractor import (
    EXTRACTOR_VERSION_PREFIXES,
    GOLD_EXTRACTOR_PREFIX,
    HUMAN_EXTRACTOR_PREFIX,
    WEB_EXTRACTOR_PREFIX,
)
from .field import (
    CONDITION_DIMENSION_NAMES,
    CanonicalField,
    Condition,
    ConditionDimensions,
    ConflictCandidate,
    ConflictQueueEntry,
    DeclaredBand,
    DeclaredBandUnitError,
    Resolution,
    SourceRef,
    VocabularyError,
)
from .principal import PrincipalContext
from .sql_freeze import (
    CLAIM_HUMAN_RESOLUTION_CHECK,
    CLAIM_HUMAN_RESOLUTION_CONSTRAINT,
    RUN_EVENT_TYPES,
    SQL_RESERVED_FILES,
)
from .table import CellSpan, TableData

__all__ = [
    "CATEGORY_TO_TAB",
    "CLAIM_HUMAN_RESOLUTION_CHECK",
    "CLAIM_HUMAN_RESOLUTION_CONSTRAINT",
    "CONDITION_DIMENSION_NAMES",
    "EXTRACTOR_VERSION_PREFIXES",
    "GOLD_EXTRACTOR_PREFIX",
    "HUMAN_EXTRACTOR_PREFIX",
    "RUN_EVENT_TYPES",
    "SQL_RESERVED_FILES",
    "WEB_EXTRACTOR_PREFIX",
    "CanonicalField",
    "CellFlag",
    "CellSpan",
    "ChunkRecord",
    "ComponentCategory",
    "ComponentInstance",
    "Condition",
    "ConditionDimensions",
    "ConflictCandidate",
    "ConflictClass",
    "ConflictQueueEntry",
    "ConflictStatus",
    "DeclaredBand",
    "DeclaredBandUnitError",
    "DocumentType",
    "EfficiencyWeighting",
    "MeasurementBasis",
    "PowerSide",
    "PrincipalContext",
    "Resolution",
    "ResolutionAction",
    "RteBoundary",
    "Severity",
    "SourceDocument",
    "SourceRef",
    "SourceTier",
    "StandardsRegime",
    "TableData",
    "ToleranceCondition",
    "ToleranceKind",
    "ToleranceRule",
    "UnencodableValueError",
    "UnresolvedStatus",
    "VocabularyError",
    "WorkbookTab",
    "encode_value",
]
